### ISSUE TITLE
Still can lock/lock, turn on/of engine without keys

### ISSUE THREAD

**Issue by riiain** [hoangducdt/MojiaVehicleKeys#10]
Can u help me about this problem?

**Comment by Duruteu** [comment]
Hello friend, I also had this problem, I managed to solve it, but now the work vehicles do not work without the key

**Comment by Duruteu** [comment]
I blocked this function "RegisterNetEvent('vehiclekeys:client:SetOwner', function(plate) --Event of qb-vehiclekeys
    AddTempKey(plate)
end)" keys work normally i'm just having problems with work vehicles that won't start without the key

**Comment by hoangducvn** [comment]
Vehicles for temporary use will not need a key. For example, the vehicle has been lockpick, the vehicle is for work...
