### ISSUE TITLE
error in F8

### ISSUE THREAD

**Issue by Duruteu** [hoangducdt/MojiaVehicleKeys#12]
Does anyone know how to get rid of this error?
I did the whole tutorial I don't know where I went wrong
![20220224185852_1](https://user-images.githubusercontent.com/31866110/155615022-ab8e1f9f-6f22-4304-a2ca-6f0f5e11640c.jpg)

**Comment by hoangducvn** [comment]
![image](https://user-images.githubusercontent.com/32219904/155711051-1f01f36a-20b4-4f51-b98d-c28be586e434.png)
Line 1538? Make sure you've updated everything

**Comment by Duruteu** [comment]
This error appeared after I added these lines
![Captura de tela 2022-02-26 072713](https://user-images.githubusercontent.com/31866110/155839811-a02b2e1c-d002-4d51-bfca-b2e5a693720e.png)

**Comment by hoangducvn** [comment]
Replace `exports["qb-vehiclekeys"]:HasVehicleKey(plate)` with `exports['MojiaVehicleKeys']:CheckHasKey(plate)`

**Comment by Duruteu** [comment]
The error continues just changed the name of the scrip
![20220226235452_1](https://user-images.githubusercontent.com/31866110/155866360-48bffd94-c683-403d-8108-8dfb1bfe7ab7.jpg)
t

**Comment by Duruteu** [comment]
Should I export Something in the lines below? If yes, can you tell me what it is?
![Captura de tela 2022-02-26 235611](https://user-images.githubusercontent.com/31866110/155866385-593c004d-614e-4f7c-9730-fb3aaf243cbc.png)
