### ISSUE TITLE
my car won't start

### ISSUE THREAD

**Issue by Duruteu** [hoangducdt/MojiaVehicleKeys#4]
I did all the tutorial but my car won't start

**Comment by hoangducvn** [comment]
Is your car the car before or after using this script? if it's a car before using this script, go to the pillbox garage to get the key, because without the key you won't be able to start the car

**Comment by Duruteu** [comment]
I deleted my character and made another one I went to the store and bought another car but the problem remains

**Comment by Duruteu** [comment]
I don't know what I did wrong, I'll install everything from scratch to see where I went wrong

**Comment by Duruteu** [comment]
Is it necessary to remove the qb-vehiclekeys script or it has to remain together?

**Comment by hoangducvn** [comment]
> Is it necessary to remove the qb-vehiclekeys script or it has to remain together?

no qb-vehiclekeys script needed

**Comment by Duruteu** [comment]
I managed to get it to work my only problem now is that even without the key I can start the car

**Comment by Duruteu** [comment]
I made another server and configured it from scratch the problem was solved
