### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by madalex24** [hoangducdt/MojiaVehicleKeys#8]
I followed the script edits to the letter but when I load up it comes up in my f8 
![Screenshot 2022-02-16 084453](https://user-images.githubusercontent.com/91700454/154228557-8fe994cc-edb8-4322-b6d4-89aa395e649d.png)

Please help

**Comment by hoangducvn** [comment]
make sure you used https://github.com/BerkieBb/qb-target

**Comment by madalex24** [comment]
All sorted now
